name: Unit Tests

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/**'

  # pull_request:
  #   paths:
  #     - '**/*.cs'
  #     - '**/*.csproj'
  #     - '.github/workflows/**'

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # 不安装对应的windowsappruntime会导致单测一直卡住background
      # 估计是MemeManager要单测的部分依赖了winui3 sdk部分导致的
      # 暂时先这样, 后面单独把ui无关部分拆成MemeManager.Core 就可以移除这个安装步骤了
      - name: Cache WindowsAppRuntime installer
        id: cache-warp
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\WindowsAppRuntimeInstall.exe
          key: windowsappruntime-2.3-x64

      - name: Install WindowsAppRuntime 2.3
        shell: pwsh
        run: |
          $exe = "$env:RUNNER_TEMP\WindowsAppRuntimeInstall.exe"
          if (-not (Test-Path $exe)) {
            Invoke-WebRequest -Uri "https://aka.ms/windowsappsdk/2.3/latest/windowsappruntimeinstall-x64.exe" -OutFile $exe
          }
          & $exe --quiet --force
          Start-Sleep -Seconds 3
      - name: Run unit tests
        run: dotnet test MemeManager.Tests/MemeManager.Tests.csproj -p:Platform=x64 --nologo
